from llm.prompt.models.conversation import Conversation
from llm.prompt.models.message import Message


class ConversationGuard:
    """
    Maintains the short-term conversation context.

    The most recent N messages remain intact.
    Older messages are identified for compaction and can
    later be replaced by a generated summary.
    """

    def __init__(
        self,
        max_recent_messages: int = 8,
    ) -> None:
        if max_recent_messages <= 0:
            raise ValueError(
                "max_recent_messages must be greater than 0."
            )

        self.max_recent_messages = max_recent_messages

    def needs_compaction(
        self,
        conversation: Conversation,
    ) -> bool:
        """
        Return True when the conversation contains more
        messages than the configured recent-message limit.
        """

        return (
            len(conversation.messages)
            > self.max_recent_messages
        )

    def get_messages_to_compact(
        self,
        conversation: Conversation,
    ) -> list[Message]:
        """
        Return the older messages that should be compacted.

        The most recent N messages are never included.
        """

        if not self.needs_compaction(conversation):
            return []

        split_index = (
            len(conversation.messages)
            - self.max_recent_messages
        )

        return conversation.messages[
            :split_index
        ]

    def get_recent_messages(
        self,
        conversation: Conversation,
    ) -> list[Message]:
        """
        Return the most recent N messages that should
        remain intact.
        """

        if len(conversation.messages) <= (
            self.max_recent_messages
        ):
            return list(conversation.messages)

        return conversation.messages[
            -self.max_recent_messages:
        ]

    def apply_summary(
        self,
        conversation: Conversation,
        summary: str,
    ) -> Conversation:
        """
        Apply a generated summary and retain only the
        most recent configured number of messages.

        The summary must already have been generated by
        the LLM. This method does not call any LLM.
        """

        if not summary.strip():
            raise ValueError(
                "Summary cannot be empty."
            )

        conversation.summary = summary.strip()

        conversation.messages = (
            self.get_recent_messages(
                conversation
            )
        )

        return conversation